name: 📦 Deploy Application

on:
  workflow_run:
    workflows: ["🐋 Build Docker Image"]
    branches: 
      - main
    types: 
      - completed
  
jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
      env:
        DIRECTORY: ${{ secrets.DIRECTORY }}
      port: 22
      script: |
        cd $DIRECTORY
        docker compose pull
        docker compose down
        docker compose up -d